---
AWSTemplateFormatVersion: "2010-09-09"

Description: A single S3 bucket stack

Parameters:
  jhS3BucketName:
    Type: String
    Default: "jhs3bucket"

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref AWS::Region, !Ref AWS::AccountId, !Ref jhS3BucketName]]
